image: debian:stretch


GNU/Linux build:
  before_script:
   - apt-get update -qq
   - apt-get install -y -qq abi-compliance-checker pkg-config gcc make gettext autopoint git autoconf automake libtool texinfo gperf libunistring-dev help2man gtk-doc-tools valgrind gengetopt
   - ./bootstrap
  script:
  - ./bootstrap && ./configure --enable-gtk-doc --enable-gtk-doc-pdf --enable-gcc-warnings --enable-valgrind-tests && make -j$(nproc) check
  - make abi-check
  tags:
  - shared
  artifacts:
    expire_in: 2 weeks
    when: on_failure
    paths:
      - tests/*.log
      - compat_reports/

ASAN build:
  before_script:
   - apt-get update -qq
   - apt-get install -y -qq libasan3 pkg-config gcc make gettext autopoint git autoconf automake libtool texinfo gperf libunistring-dev help2man valgrind gengetopt
   - ./bootstrap
  script:
  - CFLAGS="-fsanitize=address -g -O2" ./configure --enable-gcc-warnings && make -j$(nproc) check
  tags:
  - shared
  artifacts:
    expire_in: 2 weeks
    when: on_failure
    paths:
      - tests/*.log
      - compat_reports/

UBSAN build:
  before_script:
   - apt-get update -qq
   - apt-get install -y -qq libubsan0 pkg-config gcc make gettext autopoint git autoconf automake libtool texinfo gperf help2man libunistring-dev gengetopt
   - ./bootstrap
  script:
  - CFLAGS="-fsanitize=undefined -fno-sanitize-recover -g -O2" ./configure --enable-gcc-warnings && make -j$(nproc) check
  tags:
  - shared
  artifacts:
    expire_in: 2 weeks
    when: on_failure
    paths:
      - tests/*.log
      - compat_reports/

MinGW64:
  image: fedora:25
  before_script:
  - dnf install -y git which coreutils which autoconf libtool gettext-devel automake autogen gawk gperf help2man elfutils binutils wine mingw64-gcc mingw64-iconv util-linux gengetopt
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc &&
    echo ':DOSWin:M::MZ::/usr/bin/wine64:' > /proc/sys/fs/binfmt_misc/register
  - ./bootstrap
  script:
  - mingw64-configure --disable-valgrind-tests --disable-doc
  - mingw64-make -j$(nproc)
  - mingw64-make -j$(nproc) check
  tags:
  - shared
  - docker
  except:
  - tags
  artifacts:
    expire_in: 2 weeks
    when: on_failure
    paths:
      - ./*.log
      - tests/*.log
