GNU/Linux build:
  before_script:
    - apt-get update -qq && apt-get install -y -qq git autoconf automake libtool texinfo gperf libunistring-dev help2man gtk-doc-tools valgrind gengetopt
  script:
  - ./bootstrap && ./configure --enable-gtk-doc --enable-gtk-doc-pdf --enable-gcc-warnings --enable-valgrind-tests && make -j$(nproc) check
  tags:
  - linux
  artifacts:
    expire_in: 1 month
    when: on_failure
    paths:
      - tests/*.log

