sudo: required
dist: focal

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

git:
    depth: 3

matrix:
    exclude:
        - os: osx
          compiler: gcc

cache: ccache

addons:
    apt:
        packages:
            - git
	    - autoconf
	    - automake
	    - libtool
	    - gettext
	    - texinfo
	    - gperf
	    - libunistring-dev
	    - gtk-doc-tools
	    - valgrind
	    - gengetopt
	    - help2man
	    - abi-compliance-checker
	    - autopoint
	    - texlive
	    - abigail-tools
            - lcov

before_install:
  - echo $TRAVIS_OS_NAME
  - ./.travis_setup.sh

script: ./.travis.sh
